config/routes.rb
SampleApp::Application.routes.draw do
  resources :pins

  devise_for :users
  

  root :to => "pages#home"
  get "about" => "pages#about"

end

app/models/pin.rb
class Pin < ActiveRecord::Base
  attr_accessible :description
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

   def about
  end
end

app/controllers/pins_controller.rb
class PinsController < ApplicationController

  def index
    @pins = Pin.all
  end

  
  def show
    @pin = Pin.find(params[:id])
  end

 
  def new
    @pin = Pin.new
  end

  
  def edit
    @pin = Pin.find(params[:id])
  end

  
  def create
    @pin = Pin.new(params[:pin])
      if @pin.save
          redirect_to @pin, notice: 'Pin was successfully created.'
      else
         render action: "new"
      end
  end

 
  def update
    @pin = Pin.find(params[:id])
      if @pin.update_attributes(params[:pin])
          redirect_to @pin, notice: 'Pin was successfully updated.'
      else
        render action: "edit"
      end    
  end

  
  def destroy
    @pin = Pin.find(params[:id])
    @pin.destroy
      redirect_to pins_url
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "SampleApp", root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      
      
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "HOME", root_path %></li>
        <li><%= link_to "ABOUT", about_path %></li>

        <% if user_signed_in? %>
        <li><%= link_to "Account Setting", edit_user_registration_path %></li>
        <li><%= link_to "LOGOUT", destroy_user_session_path, :method => :delete %></li>
            <% else %>

            <li><%= link_to "Sign up", new_user_session_path %></li>
            <% end %>


        
      
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SampleApp</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag :default %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>
<%= render 'layouts/header' %>
<div class="container">
	<%flash.each do |name,msg| %>
	<%= content_tag(:div, msg, class: "alert alert-info") %>
	<% end %>
	<%= yield %>
</div>
</body>
</html>

app/views/pages/about.html.erb
<div class="jumbotron">
<h1> About us </h1>
<p> We are working on Sample_app !!</p>

app/views/pages/home.html.erb
<div class="jumbotron">
	<div class="container text-center">
<h1>Welcome to my application</h1>
<% if user_signed_in? %>
# do something
<% else %>


<p>
<%= link_to "Login",new_user_session_path, class: "btn btn-primary btn-lg" %>
<%= link_to "sign up",new_user_registration_path, class: "btn btn-primary btn-lg" %>
</p>

<% end %>
</div>

app/views/pins/_form.html.erb
<%= form_for(@pin) do |f| %>
  <% if @pin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pin.errors.count, "error") %> prohibited this pin from being saved:</h2>

      <ul>
      <% @pin.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pins/edit.html.erb
<h1>Editing pin</h1>

<%= render 'form' %>

<%= link_to 'Show', @pin %> |
<%= link_to 'Back', pins_path %>

app/views/pins/index.html.erb
<h1>Listing pins</h1>

<table>
  <tr>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @pins.each do |pin| %>
  <tr>
    <td><%= pin.description %></td>
    <td><%= link_to 'Show', pin %></td>
    <td><%= link_to 'Edit', edit_pin_path(pin) %></td>
    <td><%= link_to 'Destroy', pin, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Pin', new_pin_path %>

app/views/pins/new.html.erb
<h1>New pin</h1>

<%= render 'form' %>

<%= link_to 'Back', pins_path %>

app/views/pins/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Description:</b>
  <%= @pin.description %>
</p>


<%= link_to 'Edit', edit_pin_path(@pin) %> |
<%= link_to 'Back', pins_path %>